﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Threading.Tasks;
using Refit;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace Issues
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIIssuesApi : IIssuesApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIIssuesApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<LocationList> GetLocationsRaw()
        {
            var arguments = new object[] {  };
            return (Task<LocationList>) methodImpls["GetLocationsRaw"](Client, arguments);
        }

        public virtual Task<IssueList> GetIssuesRaw()
        {
            var arguments = new object[] {  };
            return (Task<IssueList>) methodImpls["GetIssuesRaw"](Client, arguments);
        }

        public virtual Task<Issue> CreateIssueRaw(Issue issue)
        {
            var arguments = new object[] { issue };
            return (Task<Issue>) methodImpls["CreateIssueRaw"](Client, arguments);
        }

        public virtual Task<Issue> AddPhoto(int id,Stream stream)
        {
            var arguments = new object[] { id,stream };
            return (Task<Issue>) methodImpls["AddPhoto"](Client, arguments);
        }

    }
}


